spring:
  application:
    name: phoenix-sat-backend
  datasource:
    url: jdbc:postgresql://${PHOENIX_BACKEND_DB_HOST}:${PHOENIX_BACKEND_DB_PORT}/${PHOENIX_BACKEND_DB_NAME}?currentSchema=${PHOENIX_BACKEND_DB_SCHEMA}
    username: ${PHOENIX_BACKEND_DB_USERNAME}
    password: ${PHOENIX_BACKEND_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    hibernate:
      ddl-auto: none
    open-in-view:
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    default-schema: ${PHOENIX_BACKEND_DB_SCHEMA}
    liquibase-schema: ${PHOENIX_BACKEND_DB_SCHEMA}
    enabled: true


security:
  auth:
    whitelist: >
      /swagger-resources,
      /swagger-resources/**,
      /configuration/ui,  
      /configuration/security,
      /swagger-ui.html,
      /webjars/**,
      /api/public/**,
      /v3/api-docs/**,
      /v3/api-docs,
      /swagger-ui/**,
      /v2/api-docs,
      /api/v1/public/**,
      /ws-registration/**,
      /api/v1/public/accounts/**

  jwt:
    secret-key: ${PHOENIX_BACKEND_JWT_SECRET_KEY}
app:
  organization:
    default-id: ${PHOENIX_BACKEND_DEFAULT_ORGANIZATION_ID}