
INSERT INTO country (code, name_en, name_az, name_ru) VALUES
('AF', 'Afghanistan', 'Əfqanıstan', 'Афганистан'),
('AL', 'Albania', 'Albaniya', 'Албания'),
('DZ', 'Algeria', 'Əlcəzair', 'Алжир'),
('AD', 'Andorra', 'Andorra', 'Андорра'),
('AO', 'Angola', 'Anqola', 'Ангола'),
('AG', 'Antigua and Barbuda', 'Antiqua və Barbuda', 'Антигуа и Барбуда'),
('AR', 'Argentina', 'Argentina', 'Аргентина'),
('AM', 'Armenia', 'Ermənistan', 'Армения'),
('AU', 'Australia', 'Avstraliya', 'Австралия'),
('AT', 'Austria', 'Avstriya', 'Австрия'),
('AZ', 'Azerbaijan', 'Azərbaycan', 'Азербайджан'),
('BS', 'Bahamas', 'Baham adaları', 'Багамы'),
('BH', 'Bahrain', 'Bəhreyn', 'Бахрейн'),
('BD', 'Bangladesh', 'Banqladeş', 'Бангладеш'),
('BB', 'Barbados', 'Barbados', 'Барбадос'),
('BY', 'Belarus', 'Belarus', 'Беларусь'),
('BE', 'Belgium', 'Belçika', 'Бельгия'),
('BZ', 'Belize', 'Beliz', 'Белиз'),
('BJ', 'Benin', 'Benin', 'Бенин'),
('BT', 'Bhutan', 'Butan', 'Бутан'),
('BO', 'Bolivia', 'Boliviya', 'Боливия'),
('BA', 'Bosnia and Herzegovina', 'Bosniya və Herseqovina', 'Босния и Герцеговина'),
('BW', 'Botswana', 'Botsvana', 'Ботсвана'),
('BR', 'Brazil', 'Braziliya', 'Бразилия'),
('BN', 'Brunei', 'Bruney', 'Бруней'),
('BG', 'Bulgaria', 'Bolqarıstan', 'Болгария'),
('BF', 'Burkina Faso', 'Burkina Faso', 'Буркина-Фасо'),
('BI', 'Burundi', 'Burundi', 'Бурунди'),
('KH', 'Cambodia', 'Kamboca', 'Камбоджа'),
('CM', 'Cameroon', 'Kamerun', 'Камерун'),
('CA', 'Canada', 'Kanada', 'Канада'),
('CV', 'Cape Verde', 'Kabo-Verde', 'Кабо-Верде'),
('CF', 'Central African Republic', 'Mərkəzi Afrika Respublikası', 'Центральноафриканская Республика'),
('TD', 'Chad', 'Çad', 'Чад'),
('CL', 'Chile', 'Çili', 'Чили'),
('CN', 'China', 'Çin', 'Китай'),
('CO', 'Colombia', 'Kolumbiya', 'Колумбия'),
('KM', 'Comoros', 'Komor adaları', 'Коморы'),
('CG', 'Congo', 'Konqo', 'Конго'),
('CD', 'Congo, Democratic Republic', 'Konqo Demokratik Respublikası', 'Демократическая Республика Конго'),
('CR', 'Costa Rica', 'Kosta Rika', 'Коста-Рика'),
('HR', 'Croatia', 'Xorvatiya', 'Хорватия'),
('CU', 'Cuba', 'Kuba', 'Куба'),
('CY', 'Cyprus', 'Kipr', 'Кипр'),
('CZ', 'Czech Republic', 'Çexiya', 'Чехия'),
('DK', 'Denmark', 'Danimarka', 'Дания'),
('DJ', 'Djibouti', 'Cibuti', 'Джибути'),
('DM', 'Dominica', 'Dominika', 'Доминика'),
('DO', 'Dominican Republic', 'Dominikan Respublikası', 'Доминиканская Республика'),
('EC', 'Ecuador', 'Ekvador', 'Эквадор'),
('EG', 'Egypt', 'Misir', 'Египет'),
('SV', 'El Salvador', 'El Salvador', 'Сальвадор'),
('GQ', 'Equatorial Guinea', 'Ekvatorial Qvineya', 'Экваториальная Гвинея'),
('ER', 'Eritrea', 'Eritreya', 'Эритрея'),
('EE', 'Estonia', 'Estoniya', 'Эстония'),
('SZ', 'Eswatini', 'Esvatini', 'Эсватини'),
('ET', 'Ethiopia', 'Efiopiya', 'Эфиопия'),
('FJ', 'Fiji', 'Fici', 'Фиджи'),
('FI', 'Finland', 'Finlandiya', 'Финляндия'),
('FR', 'France', 'Fransa', 'Франция'),
('GA', 'Gabon', 'Qabon', 'Габон'),
('GM', 'Gambia', 'Qambiya', 'Гамбия'),
('GE', 'Georgia', 'Gürcüstan', 'Грузия'),
('DE', 'Germany', 'Almaniya', 'Германия'),
('GH', 'Ghana', 'Qana', 'Гана'),
('GR', 'Greece', 'Yunanıstan', 'Греция'),
('GD', 'Grenada', 'Qrenada', 'Гренада'),
('GT', 'Guatemala', 'Qvatemala', 'Гватемала'),
('GN', 'Guinea', 'Qvineya', 'Гвинея'),
('GW', 'Guinea-Bissau', 'Qvineya-Bisau', 'Гвинея-Бисау'),
('GY', 'Guyana', 'Qayana', 'Гайана'),
('HT', 'Haiti', 'Haiti', 'Гаити'),
('HN', 'Honduras', 'Honduras', 'Гондурас'),
('HU', 'Hungary', 'Macarıstan', 'Венгрия'),
('IS', 'Iceland', 'İslandiya', 'Исландия'),
('IN', 'India', 'Hindistan', 'Индия'),
('ID', 'Indonesia', 'İndoneziya', 'Индонезия'),
('IR', 'Iran', 'İran', 'Иран'),
('IQ', 'Iraq', 'İraq', 'Ирак'),
('IE', 'Ireland', 'İrlandiya', 'Ирландия'),
('IL', 'Israel', 'İsrail', 'Израиль'),
('IT', 'Italy', 'İtaliya', 'Италия'),
('JM', 'Jamaica', 'Yamayka', 'Ямайка'),
('JP', 'Japan', 'Yaponiya', 'Япония'),
('JO', 'Jordan', 'İordaniya', 'Иордания'),
('KZ', 'Kazakhstan', 'Qazaxıstan', 'Казахстан'),
('KE', 'Kenya', 'Keniya', 'Кения'),
('KI', 'Kiribati', 'Kiribati', 'Кирибати'),
('KP', 'North Korea', 'Şimali Koreya', 'Северная Корея'),
('KR', 'South Korea', 'Cənubi Koreya', 'Южная Корея'),
('KW', 'Kuwait', 'Küveyt', 'Кувейт'),
('KG', 'Kyrgyzstan', 'Qırğızıstan', 'Киргизия'),
('LA', 'Laos', 'Laos', 'Лаос'),
('LV', 'Latvia', 'Latviya', 'Латвия'),
('LB', 'Lebanon', 'Livan', 'Ливан'),
('LS', 'Lesotho', 'Lesoto', 'Лесото'),
('LR', 'Liberia', 'Liberiya', 'Либерия'),
('LY', 'Libya', 'Liviya', 'Ливия'),
('LI', 'Liechtenstein', 'Lixtenşteyn', 'Лихтенштейн'),
('LT', 'Lithuania', 'Litva', 'Литва'),
('LU', 'Luxembourg', 'Lüksemburq', 'Люксембург'),
('MG', 'Madagascar', 'Madaqaskar', 'Мадагаскар'),
('MW', 'Malawi', 'Malavi', 'Малави'),
('MY', 'Malaysia', 'Malayziya', 'Малайзия'),
('MV', 'Maldives', 'Maldiv adaları', 'Мальдивы'),
('ML', 'Mali', 'Mali', 'Мали'),
('MT', 'Malta', 'Malta', 'Мальта'),
('MH', 'Marshall Islands', 'Marşal Adaları', 'Маршалловы Острова'),
('MR', 'Mauritania', 'Mavritaniya', 'Мавритания'),
('MU', 'Mauritius', 'Mavriki', 'Маврикий'),
('MX', 'Mexico', 'Meksika', 'Мексика'),
('FM', 'Micronesia', 'Mikroneziya', 'Микронезия'),
('MD', 'Moldova', 'Moldova', 'Молдова'),
('MC', 'Monaco', 'Monako', 'Монако'),
('MN', 'Mongolia', 'Monqolustan', 'Монголия'),
('ME', 'Montenegro', 'Monteneqro', 'Черногория'),
('MA', 'Morocco', 'Mərakeş', 'Марокко'),
('MZ', 'Mozambique', 'Mozambik', 'Мозамбик'),
('MM', 'Myanmar', 'Myanma', 'Мьянма'),
('NA', 'Namibia', 'Namibiya', 'Намибия'),
('NR', 'Nauru', 'Nauru', 'Науру'),
('NP', 'Nepal', 'Nepal', 'Непал'),
('NL', 'Netherlands', 'Niderland', 'Нидерланды'),
('NZ', 'New Zealand', 'Yeni Zelandiya', 'Новая Зеландия'),
('NI', 'Nicaragua', 'Nikaraqua', 'Никарагуа'),
('NE', 'Niger', 'Niger', 'Нигер'),
('NG', 'Nigeria', 'Nigeriya', 'Нигерия'),
('MK', 'North Macedonia', 'Şimali Makedoniya', 'Северная Македония'),
('NO', 'Norway', 'Norveç', 'Норвегия'),
('OM', 'Oman', 'Oman', 'Оман'),
('PK', 'Pakistan', 'Pakistan', 'Пакистан'),
('PW', 'Palau', 'Palau', 'Палау'),
('PA', 'Panama', 'Panama', 'Панама'),
('PG', 'Papua New Guinea', 'Papua-Yeni Qvineya', 'Папуа-Новая Гвинея'),
('PY', 'Paraguay', 'Paraqvay', 'Парагвай'),
('PE', 'Peru', 'Peru', 'Перу'),
('PH', 'Philippines', 'Filippin', 'Филиппины'),
('PL', 'Poland', 'Polşa', 'Польша'),
('PT', 'Portugal', 'Portuqaliya', 'Португалия'),
('QA', 'Qatar', 'Qətər', 'Катар'),
('RO', 'Romania', 'Rumıniya', 'Румыния'),
('RU', 'Russia', 'Rusiya', 'Россия'),
('RW', 'Rwanda', 'Ruanda', 'Руанда'),
('KN', 'Saint Kitts and Nevis', 'Sent-Kits və Nevis', 'Сент-Китс и Невис'),
('LC', 'Saint Lucia', 'Sent-Lüsiya', 'Сент-Люсия'),
('VC', 'Saint Vincent and the Grenadines', 'Sent-Vinsent və Qrenadinlər', 'Сент-Винсент и Гренадины'),
('WS', 'Samoa', 'Samoa', 'Самоа'),
('SM', 'San Marino', 'San Marino', 'Сан-Марино'),
('ST', 'Sao Tome and Principe', 'San-Tome və Prinsipi', 'Сан-Томе и Принсипи'),
('SA', 'Saudi Arabia', 'Səudiyyə Ərəbistanı', 'Саудовская Аравия'),
('SN', 'Senegal', 'Seneqal', 'Сенегал'),
('RS', 'Serbia', 'Serbiya', 'Сербия'),
('SC', 'Seychelles', 'Seyşel adaları', 'Сейшелы'),
('SL', 'Sierra Leone', 'Sierra Leone', 'Сьерра-Леоне'),
('SG', 'Singapore', 'Sinqapur', 'Сингапур'),
('SK', 'Slovakia', 'Slovakiya', 'Словакия'),
('SI', 'Slovenia', 'Sloveniya', 'Словения'),
('SB', 'Solomon Islands', 'Solomon adaları', 'Соломоновы Острова'),
('SO', 'Somalia', 'Somali', 'Сомали'),
('ZA', 'South Africa', 'Cənubi Afrika', 'Южная Африка'),
('SS', 'South Sudan', 'Cənubi Sudan', 'Южный Судан'),
('ES', 'Spain', 'İspaniya', 'Испания'),
('LK', 'Sri Lanka', 'Şri-Lanka', 'Шри-Ланка'),
('SD', 'Sudan', 'Sudan', 'Судан'),
('SR', 'Suriname', 'Surinam', 'Суринам'),
('SE', 'Sweden', 'İsveç', 'Швеция'),
('CH', 'Switzerland', 'İsveçrə', 'Швейцария'),
('SY', 'Syria', 'Suriya', 'Сирия'),
('TJ', 'Tajikistan', 'Tacikistan', 'Таджикистан'),
('TZ', 'Tanzania', 'Tanzaniya', 'Танзания'),
('TH', 'Thailand', 'Tailand', 'Таиланд'),
('TL', 'Timor-Leste', 'Şərqi Timor', 'Восточный Тимор'),
('TG', 'Togo', 'Toqo', 'Того'),
('TO', 'Tonga', 'Tonqa', 'Тонга'),
('TT', 'Trinidad and Tobago', 'Trinidad və Tobaqo', 'Тринидад и Тобаго'),
('TN', 'Tunisia', 'Tunis', 'Тунис'),
('TR', 'Turkey', 'Türkiyə', 'Турция'),
('TM', 'Turkmenistan', 'Türkmənistan', 'Туркмения'),
('TV', 'Tuvalu', 'Tuvalu', 'Тувалу'),
('UG', 'Uganda', 'Uqanda', 'Уганда'),
('UA', 'Ukraine', 'Ukrayna', 'Украина'),
('AE', 'United Arab Emirates', 'Birləşmiş Ərəb Əmirlikləri', 'Объединённые Арабские Эмираты'),
('GB', 'United Kingdom', 'Böyük Britaniya', 'Великобритания'),
('US', 'United States', 'Amerika Birləşmiş Ştatları', 'Соединённые Штаты Америки'),
('UY', 'Uruguay', 'Uruqvay', 'Уругвай'),
('UZ', 'Uzbekistan', 'Özbəkistan', 'Узбекистан'),
('VU', 'Vanuatu', 'Vanuatu', 'Вануату'),
('VA', 'Vatican City', 'Vatikan', 'Ватикан'),
('VE', 'Venezuela', 'Venesuela', 'Венесуэла'),
('VN', 'Vietnam', 'Vyetnam', 'Вьетнам'),
('YE', 'Yemen', 'Yəmən', 'Йемен'),
('ZM', 'Zambia', 'Zambiya', 'Замбия'),
('ZW', 'Zimbabwe', 'Zimbabve', 'Зимбабве');

